[package]
name = "rsbuster"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
env_logger = "0.11.5"
indicatif = "0.17.9"
indicatif-log-bridge = "0.2.3"
log = "0.4.22"
reqwest = "0.12.9"
tokio = { version = "1.41.1", features = ["full"] }
